# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['_tmpl'],
    extraSrc={'_tmpl': ["_ExampleOne.cc", "_ExampleTwo.cc", "_ExampleThree.cc"]},
    addUnderscore=False
)
